Switched around/added icons
kauwelab/PolyRiskScore pull request #305
Opened 2021-04-23 20:55 UTC by mpage21

GWAS studies to GWA studies

2021-04-23 20:57 UTC, mpage21 commented
![Screenshot (209)](https://user-images.githubusercontent.com/23090557/115928928-2925b300-a444-11eb-8b89-255e19f741e0.png)

Here is a visual of the updated icons

2021-04-23 22:24 UTC, MattCloward requested changes
This looks great! See my one comment.

2021-04-23 22:24 UTC, MattCloward commented on static/index.html
> +                <!-- <p>Download our API to submit your VCF files to the analysis pipeline via the command line.</p> -->
Can this comment be removed?

2021-04-24 01:01 UTC, mpage21 commented on static/index.html
> +                <!-- <p>Download our API to submit your VCF files to the analysis pipeline via the command line.</p> -->
yes

2021-04-24 01:03 UTC, merged