Server endpoint exclude duplicates
kauwelab/PolyRiskScore pull request #322
Opened 2021-05-17 20:40 UTC by mpage21

After this is merged, I'll run the code to create the all associations files

2021-05-17 22:10 UTC, lizvance reviewed
Just the one comma that needs to be added! Nice work :)

2021-05-17 22:10 UTC, lizvance commented on README.md
> +The Calculate page of the PRSKB website allows the user to calculate polygenic risk scores for multiple samples across more than 2100 trait/study combinations. Using an input VCF or inputted rsIDs an
comma after "and selected studies"

2021-05-18 03:24 UTC, MattCloward commented on static/js/controllers/associations.controller.js
> +                        // TODO we will need to put in the documentation that the symbol we use for duplicated snps should indicate that we have excluded those duplicated snps
Have you completed this TODO?

2021-05-18 03:27 UTC, MattCloward commented on static/js/controllers/associations.controller.js
> +            //todo check if this is the right logic
Have you done this TODO?

2021-05-18 03:30 UTC, MattCloward requested changes
There are two TODOs that need to be addressed and removed. Other than that, this looks good!

2021-05-19 16:00 UTC, merged